module.exports = {
  INITIALIZE: "INITIALIZE",
  NEW_USER: "NEW_USER",
  REGISTER_USER_WITH_BRAND: "REGISTER_USER_WITH_BRAND",
  REDEEM: "REDEEM",
  USER_CLAIMS_SIGNET_PRODUCT: "USER_CLAIMS_SIGNET_PRODUCT",
  USER_CREATE_REWARD: "USER_CREATE_REWARD",
  USER_MINT_SIGNETS_FOR_PRODUCT_OF_BRAND: "USER_MINT_SIGNETS_FOR_PRODUCT_OF_BRAND",
  USER_REGISTER_PRODUCT_WITH_BRAND: "USER_REGISTER_PRODUCT_WITH_BRAND",
}